### ISSUE TITLE
ランチャーのコマンド候補について

### ISSUE THREAD

**Issue by rlia** [482F/flax_ahk#166]
先頭からチェックしてると思うんですが、部分一致でも絞れるようになりませんか

putty_wslというコマンドは putty…と入力したときに表示されると思うが、
wsl だけ入力したときに putty_wsl が表示されるようにするなど

**Comment by 482F** [comment]
config.fd の launcher.search_method を partial にすることで部分一致検索になる。前方一致なら prefix。
