### ISSUE TITLE
リモートデスクトップ起動時に gesture がでしゃばる

### ISSUE THREAD

**Issue by rlia** [482F/flax_ahk#174]
まれにリモートデスクトップ時に ローカル側で起動してる flax_ahk の gesture がでしゃばり、マウス操作が効かなくなる。
一度 win + L でロックすると治る

**Comment by 482F** [comment]
それ ahk 側の問題で、gesture 設定していなくとも Windows キーは押されっぱなしになる。
Win + クリックのバインドを解除すればとりあえずクリックは効くようになるけど、e 連打すると無限にエクスプローラが開いたりする。
一応 config.fd `にはホットキー変更/無効化機能がついているので、
```
ChangeHotKey=[
    *#RButton=[
        Key=Off
    ]
    *#LButton=[
        Key=Off
    ]
    *#MButton=[
        Key=Off
    ]
]
```
を書くと無効化できる。
